In [1]:
import tensorflow as tf

In [2]:
print(('Your Tensorflow Version is :{0}').format(tf.__version__))

Your Tensorflow Version is :2.4.1


In [3]:
A = tf.constant([[4,3],
                [5,2]])
A

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[4, 3],
       [5, 2]])>

In [4]:
B = tf.Variable([[4,2],
                [7,6]])
B

<tf.Variable 'Variable:0' shape=(2, 2) dtype=int32, numpy=
array([[4, 2],
       [7, 6]])>

In [7]:
AB_concat = tf.concat(values = [A,B], axis = 1)
AB_concat

<tf.Tensor: shape=(2, 4), dtype=int32, numpy=
array([[4, 3, 4, 2],
       [5, 2, 7, 6]])>

In [8]:
AB_concat = tf.concat(values = [A,B], axis = 0)
AB_concat

<tf.Tensor: shape=(4, 2), dtype=int32, numpy=
array([[4, 3],
       [5, 2],
       [4, 2],
       [7, 6]])>

In [9]:
AB_concat.shape

TensorShape([4, 2])

In [10]:
tensor = tf.zeros(shape = [4,2], dtype = tf.int32)
tensor

<tf.Tensor: shape=(4, 2), dtype=int32, numpy=
array([[0, 0],
       [0, 0],
       [0, 0],
       [0, 0]])>

In [11]:
tensor = tf.ones(shape = [4,2], dtype = tf.int32)
tensor

<tf.Tensor: shape=(4, 2), dtype=int32, numpy=
array([[1, 1],
       [1, 1],
       [1, 1],
       [1, 1]])>

In [12]:
reshaped_tensor = tf.reshape(tensor = tensor, shape = [2,4])
reshaped_tensor

<tf.Tensor: shape=(2, 4), dtype=int32, numpy=
array([[1, 1, 1, 1],
       [1, 1, 1, 1]])>

In [16]:
tensor = tf.random.uniform(shape = [5,6], dtype = tf.float64)
tensor

<tf.Tensor: shape=(5, 6), dtype=float64, numpy=
array([[0.34072409, 0.51940979, 0.28614986, 0.13324012, 0.84932203,
        0.32456495],
       [0.69073019, 0.44752743, 0.17160485, 0.55241498, 0.0762606 ,
        0.28915878],
       [0.5264542 , 0.26936675, 0.17947219, 0.66082255, 0.51300983,
        0.05240028],
       [0.61895748, 0.02245581, 0.2996648 , 0.71044416, 0.96202818,
        0.99501446],
       [0.77268654, 0.26760521, 0.7201981 , 0.24475299, 0.71138876,
        0.39010053]])>

In [23]:
tensor = tf.random.uniform(shape = [5,5], dtype = tf.float32)
tensor

<tf.Tensor: shape=(5, 5), dtype=float32, numpy=
array([[0.9370887 , 0.8800471 , 0.87674105, 0.32422388, 0.3518362 ],
       [0.37475193, 0.7484342 , 0.247599  , 0.79082215, 0.28252006],
       [0.23409307, 0.8604803 , 0.49516022, 0.5334588 , 0.7703538 ],
       [0.72397625, 0.35714233, 0.77143526, 0.38261485, 0.89356744],
       [0.24373269, 0.702615  , 0.16390061, 0.27639258, 0.6595081 ]],
      dtype=float32)>

In [18]:
tensor_asint = tf.cast(tensor, tf.int32)
tensor_asint

<tf.Tensor: shape=(5, 6), dtype=int32, numpy=
array([[0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0]])>

In [20]:
transpose = tf.transpose(tensor)
transpose

<tf.Tensor: shape=(6, 5), dtype=float32, numpy=
array([[0.46070898, 0.93165827, 0.8306925 , 0.15150571, 0.00699091],
       [0.6855955 , 0.60940063, 0.43156075, 0.979674  , 0.38047945],
       [0.9970561 , 0.09483528, 0.23331714, 0.7989595 , 0.98147845],
       [0.11534226, 0.27450335, 0.6367023 , 0.8972391 , 0.35915005],
       [0.99459255, 0.23044252, 0.99762356, 0.88243544, 0.91379774],
       [0.10477972, 0.43060994, 0.3131827 , 0.30128086, 0.17313814]],
      dtype=float32)>

In [24]:
tensor2 = tf.random.uniform(shape = [5,5], dtype = tf.float32)
tensor2

<tf.Tensor: shape=(5, 5), dtype=float32, numpy=
array([[0.63364875, 0.10495603, 0.9031348 , 0.87386394, 0.9423748 ],
       [0.27820027, 0.22487628, 0.3222077 , 0.22739935, 0.94409347],
       [0.7903383 , 0.09008527, 0.85869145, 0.36891115, 0.3167472 ],
       [0.7122048 , 0.44841135, 0.80397546, 0.5552558 , 0.4300059 ],
       [0.38607347, 0.06194663, 0.7276566 , 0.3057505 , 0.7987819 ]],
      dtype=float32)>

In [25]:
multiplication = tf.matmul(tensor, tensor2)
multiplication

<tf.Tensor: shape=(5, 5), dtype=float32, numpy=
array([[1.8982849 , 0.54241705, 2.3994095 , 1.630051  , 2.4120996 ],
       [1.3136635 , 0.6020574 , 1.6335931 , 1.1145068 , 1.703905  ],
       [1.4564078 , 0.5496076 , 1.9033017 , 1.1146505 , 2.034553  ],
       [1.7852814 , 0.4527158 , 2.3891702 , 1.4841197 , 2.1420748 ],
       [0.9309122 , 0.36313957, 1.2893598 , 0.78834164, 1.5905905 ]],
      dtype=float32)>

In [28]:
identity_matrix  = tf.eye(num_rows = 3, num_columns = 3, dtype = tf.int32)
identity_matrix

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])>